### PR TITLE
Fix auto-registration of Avro union (etc) types

### LINKED ISSUE #689: Avro union type issue with Schema Registry
Hey there,

I accidentally posted [this issue](https://github.com/fd4s/vulcan/issues/381) in the vulcan project instead of this one so I'm cross-posting the issue here for greater visibility. The gist of it is that you cannot use sealed traits (union types) as top-level subjects when publishing to Kafka and I think this is because of Confluent's underlying serialization mechanism not having proper support for union types. I managed to work around this by using a record containing a schema but I was wondering if this is something we could improve upon since Confluent's Schema Registry does seem to correctly support union types but I believe its the Java Serializer from Confluent that has this limitation.

Thank you so much for all your hard work and this amazing library

### PR DESCRIPTION
**Pull request by bplommer**
Resolves #689 and a major motivation for #506. Overrides the entrypoint to `KafkaAvroSerializer` to use the actual writer schema rather than guessing it from the intermediate Java representation.

### CODE REVIEW

File: modules/vulcan/src/main/scala/fs2/kafka/vulcan/AvroSettings.scala [hunk 1]
```diff
@@ -103,7 +104,16 @@ sealed abstract class AvroSettings[F[_]] {
...
     * value is being serialized.
     */
-  def createAvroSerializer(isKey: Boolean): F[(KafkaAvroSerializer, SchemaRegistryClient)]
+  def createAvroSerializer(
+    isKey: Boolean,
+    writerSchema: Option[Schema]
+  ): F[(KafkaAvroSerializer, SchemaRegistryClient)]
+
+  @deprecated("use the overload that takes an optional writer schema", "2.5.0-M3")
+  final def createAvroSerializer(
```
Comment (bplommer) [inline modules/vulcan/src/main/scala/fs2/kafka/vulcan/AvroSettings.scala:113]: I think before 3.0 we should refactor some of this to expose fewer internals.

**Review by vlovgr — APPROVED** [review]
